rootProject.name = 'java-webflux-driven-adapters'

include 'sp-engine-executor'
include 'json-placeholder-api-client'

include 'lib-api-client'
include 'lib-resilience'
include 'aws-secrets'
include 'aws-parameters'
include 'aws-secrets-manager-adapter'

include 'domain'
include 'application'
include 'adapter-in-rest'
include 'bootstrap'