plugins {
    id 'java-library'
}

dependencies {
    implementation project(':application')
    implementation project(':domain')

    api libs.reactor.core

    implementation libs.support.logging

    implementation libs.boot.starter.webflux
    implementation libs.boot.validation

    implementation libs.boot.config.processor
    annotationProcessor libs.boot.config.processor

    implementation libs.projectlombok
    annotationProcessor libs.projectlombok

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor

    implementation libs.micrometer.core
    implementation libs.jackson.databind

    testImplementation libs.boot.starter.test
    testImplementation libs.reactor.test
    testImplementation libs.mockwebserver
}